// <auto-generated />
using System;
using GymApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymApp.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260601210134_AddUsuarioCrmFieldsAndRestricciones")]
    partial class AddUsuarioCrmFieldsAndRestricciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymApp.Models.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AsistenciaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistenciaId"));

                    b.Property<bool>("AccesoPermitido")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MotivoDenegacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("AsistenciaId")
                        .HasName("PK__Asistenc__72710F45116423EA");

                    b.HasIndex("UserId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("GymApp.Models.ConfiguracionAlerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("AvisarNuevaMembresia")
                        .HasColumnType("bit");

                    b.Property<bool>("AvisarNuevoPago")
                        .HasColumnType("bit");

                    b.Property<bool>("AvisarNuevoUsuario")
                        .HasColumnType("bit");

                    b.Property<string>("ChatIdDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiasSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnviarDeudasPendientes")
                        .HasColumnType("bit");

                    b.Property<bool>("EnviarNuevosMiembros")
                        .HasColumnType("bit");

                    b.Property<bool>("EnviarPagosHoy")
                        .HasColumnType("bit");

                    b.Property<bool>("EnviarProximosVencimientos")
                        .HasColumnType("bit");

                    b.Property<bool>("EnviarResumenFinanciero")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("HoraEnvio")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UltimaEjecucionReporte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimaEjecucionVencimientos")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionAlertas");
                });

            modelBuilder.Entity("GymApp.Models.Congelamiento", b =>
                {
                    b.Property<int>("CongelamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CongelamientoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CongelamientoId"));

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MembresiaId")
                        .HasColumnType("int")
                        .HasColumnName("MembresiaID");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UsuarioEmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioEmpleadoID");

                    b.HasKey("CongelamientoId")
                        .HasName("PK__Congelam__7EA0385F3FEBB624");

                    b.HasIndex("MembresiaId");

                    b.HasIndex("UsuarioEmpleadoId");

                    b.ToTable("Congelamientos");
                });

            modelBuilder.Entity("GymApp.Models.Membresia", b =>
                {
                    b.Property<int>("MembresiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MembresiaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembresiaId"));

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activa");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.Property<decimal>("PrecioAcordado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int")
                        .HasColumnName("TurnoID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MembresiaId")
                        .HasName("PK__Membresi__5AE93077CEEFAEC0");

                    b.HasIndex("PlanId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UserId");

                    b.ToTable("Membresias");
                });

            modelBuilder.Entity("GymApp.Models.PagosMembresium", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PagoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<string>("Comprobante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EsAnulado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MembresiaId")
                        .HasColumnType("int")
                        .HasColumnName("MembresiaID");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioEmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioEmpleadoID");

                    b.HasKey("PagoId")
                        .HasName("PK__PagosMem__F00B61585E3C891C");

                    b.HasIndex("MembresiaId");

                    b.HasIndex("UsuarioEmpleadoId");

                    b.ToTable("PagosMembresia");
                });

            modelBuilder.Entity("GymApp.Models.PaseDiario", b =>
                {
                    b.Property<int>("PaseDiarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaseDiarioId"));

                    b.Property<string>("ComprobanteRuta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEmpleadoId")
                        .HasColumnType("int");

                    b.HasKey("PaseDiarioId")
                        .HasName("PK_PasesDiarios");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UserId");

                    b.HasIndex("UsuarioEmpleadoId");

                    b.ToTable("PasesDiarios", (string)null);
                });

            modelBuilder.Entity("GymApp.Models.Permiso", b =>
                {
                    b.Property<string>("PermisoId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NivelPeligro")
                        .HasColumnType("int");

                    b.HasKey("PermisoId");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            PermisoId = "Usuarios.Ver",
                            Descripcion = "Ver listado y detalles de usuarios",
                            Modulo = "Usuarios",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Usuarios.Crear",
                            Descripcion = "Crear nuevos usuarios",
                            Modulo = "Usuarios",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Usuarios.Editar",
                            Descripcion = "Editar usuarios existentes",
                            Modulo = "Usuarios",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Usuarios.Eliminar",
                            Descripcion = "Eliminar usuarios",
                            Modulo = "Usuarios",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Membresias.Ver",
                            Descripcion = "Ver listado y detalles de membresías",
                            Modulo = "Membresias",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Membresias.Crear",
                            Descripcion = "Crear membresías",
                            Modulo = "Membresias",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Membresias.Renovar",
                            Descripcion = "Renovar membresías",
                            Modulo = "Membresias",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Membresias.Editar",
                            Descripcion = "Editar detalles de membresías",
                            Modulo = "Membresias",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Membresias.Congelar",
                            Descripcion = "Congelar membresía",
                            Modulo = "Membresias",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Membresias.Eliminar",
                            Descripcion = "Eliminar membresías físicamente",
                            Modulo = "Membresias",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Pagos.Ver",
                            Descripcion = "Ver listado y detalles de pagos",
                            Modulo = "Pagos",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Pagos.Crear",
                            Descripcion = "Registrar nuevos pagos",
                            Modulo = "Pagos",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Pagos.Editar",
                            Descripcion = "Editar detalles de pagos",
                            Modulo = "Pagos",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Pagos.Anular",
                            Descripcion = "Anular pagos y recalcular deudas",
                            Modulo = "Pagos",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "PasesDiarios.Ver",
                            Descripcion = "Ver listado de pases diarios",
                            Modulo = "PasesDiarios",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "PasesDiarios.Crear",
                            Descripcion = "Crear pases diarios",
                            Modulo = "PasesDiarios",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "PasesDiarios.Eliminar",
                            Descripcion = "Eliminar pases diarios",
                            Modulo = "PasesDiarios",
                            NivelPeligro = 0
                        },
                        new
                        {
                            PermisoId = "Dashboard.Ver",
                            Descripcion = "Visualizar métricas y gráficos del dashboard",
                            Modulo = "Dashboard",
                            NivelPeligro = 0
                        });
                });

            modelBuilder.Entity("GymApp.Models.Plane", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("PermiteCongelar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("PlanId")
                        .HasName("PK__Planes__755C22D76140EBD8");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("GymApp.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("General");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("StockActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ProductoId")
                        .HasName("PK__Producto__A430AE831545AAF1");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("GymApp.Models.RestriccionUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EstadoActiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaAplicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TipoRestriccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("UsuarioAplicadorId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioAplicadorID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RestriccionesUsuarios");
                });

            modelBuilder.Entity("GymApp.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A2A5A36BE");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GymApp.Models.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TurnoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TurnoId")
                        .HasName("PK__Turnos__AD3E2EB4A28DB496");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("GymApp.Models.Usuario", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CodigoQr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CodigoQR")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Dni")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("DNI");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaUltimaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ModificadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Origen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PinAcceso")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__Usuarios__1788CCAC51338C72");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasFilter("[Dni] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "NombreUsuario" }, "UQ__Usuarios__6B0F5AE03DC8E965")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GymApp.Models.UsuarioPermiso", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("PermisoId")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("UsuarioPermisos");
                });

            modelBuilder.Entity("GymApp.Models.VentasCabecera", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VentaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaId"));

                    b.Property<DateTime?>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("UsuarioEmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioEmpleadoID");

                    b.HasKey("VentaId")
                        .HasName("PK__VentasCa__5B41514CE0132551");

                    b.HasIndex("UserId");

                    b.HasIndex("UsuarioEmpleadoId");

                    b.ToTable("VentasCabecera", (string)null);
                });

            modelBuilder.Entity("GymApp.Models.VentasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetalleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("VentaID");

                    b.HasKey("DetalleId")
                        .HasName("PK__VentasDe__6E19D6FA94348278");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("VentasDetalle", (string)null);
                });

            modelBuilder.Entity("GymApp.Models.Asistencia", b =>
                {
                    b.HasOne("GymApp.Models.Usuario", "User")
                        .WithMany("Asistencia")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Asistencias_Usuarios");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApp.Models.Congelamiento", b =>
                {
                    b.HasOne("GymApp.Models.Membresia", "Membresia")
                        .WithMany("Congelamientos")
                        .HasForeignKey("MembresiaId")
                        .IsRequired()
                        .HasConstraintName("FK_Congelamientos_Membresias");

                    b.HasOne("GymApp.Models.Usuario", "UsuarioEmpleado")
                        .WithMany("Congelamientos")
                        .HasForeignKey("UsuarioEmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK_Congelamientos_Empleado");

                    b.Navigation("Membresia");

                    b.Navigation("UsuarioEmpleado");
                });

            modelBuilder.Entity("GymApp.Models.Membresia", b =>
                {
                    b.HasOne("GymApp.Models.Plane", "Plan")
                        .WithMany("Membresia")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK_Membresias_Planes");

                    b.HasOne("GymApp.Models.Turno", "Turno")
                        .WithMany("Membresia")
                        .HasForeignKey("TurnoId")
                        .IsRequired()
                        .HasConstraintName("FK_Membresias_Turnos");

                    b.HasOne("GymApp.Models.Usuario", "User")
                        .WithMany("Membresia")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Membresias_Usuarios");

                    b.Navigation("Plan");

                    b.Navigation("Turno");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApp.Models.PagosMembresium", b =>
                {
                    b.HasOne("GymApp.Models.Membresia", "Membresia")
                        .WithMany("PagosMembresia")
                        .HasForeignKey("MembresiaId")
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_Membresias");

                    b.HasOne("GymApp.Models.Usuario", "UsuarioEmpleado")
                        .WithMany("PagosMembresia")
                        .HasForeignKey("UsuarioEmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_Empleado");

                    b.Navigation("Membresia");

                    b.Navigation("UsuarioEmpleado");
                });

            modelBuilder.Entity("GymApp.Models.PaseDiario", b =>
                {
                    b.HasOne("GymApp.Models.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .IsRequired()
                        .HasConstraintName("FK_PasesDiarios_Turnos");

                    b.HasOne("GymApp.Models.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_PasesDiarios_Usuarios");

                    b.HasOne("GymApp.Models.Usuario", "UsuarioEmpleado")
                        .WithMany()
                        .HasForeignKey("UsuarioEmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PasesDiarios_Empleado");

                    b.Navigation("Turno");

                    b.Navigation("User");

                    b.Navigation("UsuarioEmpleado");
                });

            modelBuilder.Entity("GymApp.Models.RestriccionUsuario", b =>
                {
                    b.HasOne("GymApp.Models.Usuario", "Usuario")
                        .WithMany("Restricciones")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Restricciones_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GymApp.Models.Usuario", b =>
                {
                    b.HasOne("GymApp.Models.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GymApp.Models.UsuarioPermiso", b =>
                {
                    b.HasOne("GymApp.Models.Permiso", "Permiso")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymApp.Models.Usuario", "Usuario")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GymApp.Models.VentasCabecera", b =>
                {
                    b.HasOne("GymApp.Models.Usuario", "User")
                        .WithMany("VentasCabeceraUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Ventas_Cliente");

                    b.HasOne("GymApp.Models.Usuario", "UsuarioEmpleado")
                        .WithMany("VentasCabeceraUsuarioEmpleados")
                        .HasForeignKey("UsuarioEmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK_Ventas_Empleado");

                    b.Navigation("User");

                    b.Navigation("UsuarioEmpleado");
                });

            modelBuilder.Entity("GymApp.Models.VentasDetalle", b =>
                {
                    b.HasOne("GymApp.Models.Producto", "Producto")
                        .WithMany("VentasDetalles")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_Detalle_Producto");

                    b.HasOne("GymApp.Models.VentasCabecera", "Venta")
                        .WithMany("VentasDetalles")
                        .HasForeignKey("VentaId")
                        .IsRequired()
                        .HasConstraintName("FK_Detalle_Venta");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("GymApp.Models.Membresia", b =>
                {
                    b.Navigation("Congelamientos");

                    b.Navigation("PagosMembresia");
                });

            modelBuilder.Entity("GymApp.Models.Permiso", b =>
                {
                    b.Navigation("UsuarioPermisos");
                });

            modelBuilder.Entity("GymApp.Models.Plane", b =>
                {
                    b.Navigation("Membresia");
                });

            modelBuilder.Entity("GymApp.Models.Producto", b =>
                {
                    b.Navigation("VentasDetalles");
                });

            modelBuilder.Entity("GymApp.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GymApp.Models.Turno", b =>
                {
                    b.Navigation("Membresia");
                });

            modelBuilder.Entity("GymApp.Models.Usuario", b =>
                {
                    b.Navigation("Asistencia");

                    b.Navigation("Congelamientos");

                    b.Navigation("Membresia");

                    b.Navigation("PagosMembresia");

                    b.Navigation("Restricciones");

                    b.Navigation("UsuarioPermisos");

                    b.Navigation("VentasCabeceraUsers");

                    b.Navigation("VentasCabeceraUsuarioEmpleados");
                });

            modelBuilder.Entity("GymApp.Models.VentasCabecera", b =>
                {
                    b.Navigation("VentasDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
