// <auto-generated />
using System;
using GymApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymApp.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260425165023_AddSoftDeleteYObservacionesAPagos")]
    partial class AddSoftDeleteYObservacionesAPagos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymApp.Models.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AsistenciaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistenciaId"));

                    b.Property<bool>("AccesoPermitido")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MotivoDenegacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("AsistenciaId")
                        .HasName("PK__Asistenc__72710F45116423EA");

                    b.HasIndex("UserId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("GymApp.Models.Congelamiento", b =>
                {
                    b.Property<int>("CongelamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CongelamientoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CongelamientoId"));

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MembresiaId")
                        .HasColumnType("int")
                        .HasColumnName("MembresiaID");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UsuarioEmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioEmpleadoID");

                    b.HasKey("CongelamientoId")
                        .HasName("PK__Congelam__7EA0385F3FEBB624");

                    b.HasIndex("MembresiaId");

                    b.HasIndex("UsuarioEmpleadoId");

                    b.ToTable("Congelamientos");
                });

            modelBuilder.Entity("GymApp.Models.Membresia", b =>
                {
                    b.Property<int>("MembresiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MembresiaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembresiaId"));

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activa");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    b.Property<decimal>("PrecioAcordado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int")
                        .HasColumnName("TurnoID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("MembresiaId")
                        .HasName("PK__Membresi__5AE93077CEEFAEC0");

                    b.HasIndex("PlanId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("UserId");

                    b.ToTable("Membresias");
                });

            modelBuilder.Entity("GymApp.Models.PagosMembresium", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PagoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<string>("Comprobante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EsAnulado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MembresiaId")
                        .HasColumnType("int")
                        .HasColumnName("MembresiaID");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioEmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioEmpleadoID");

                    b.HasKey("PagoId")
                        .HasName("PK__PagosMem__F00B61585E3C891C");

                    b.HasIndex("MembresiaId");

                    b.HasIndex("UsuarioEmpleadoId");

                    b.ToTable("PagosMembresia");
                });

            modelBuilder.Entity("GymApp.Models.Plane", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<int>("DuracionDias")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("PermiteCongelar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("PlanId")
                        .HasName("PK__Planes__755C22D76140EBD8");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("GymApp.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("General");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("StockActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ProductoId")
                        .HasName("PK__Producto__A430AE831545AAF1");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("GymApp.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A2A5A36BE");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GymApp.Models.Turno", b =>
                {
                    b.Property<int>("TurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TurnoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TurnoId")
                        .HasName("PK__Turnos__AD3E2EB4A28DB496");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("GymApp.Models.Usuario", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<Guid?>("CodigoQr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CodigoQR")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Dni")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("DNI");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__Usuarios__1788CCAC51338C72");

                    b.HasIndex("Dni")
                        .IsUnique()
                        .HasFilter("[Dni] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "NombreUsuario" }, "UQ__Usuarios__6B0F5AE03DC8E965")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GymApp.Models.VentasCabecera", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VentaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaId"));

                    b.Property<DateTime?>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int>("UsuarioEmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioEmpleadoID");

                    b.HasKey("VentaId")
                        .HasName("PK__VentasCa__5B41514CE0132551");

                    b.HasIndex("UserId");

                    b.HasIndex("UsuarioEmpleadoId");

                    b.ToTable("VentasCabecera", (string)null);
                });

            modelBuilder.Entity("GymApp.Models.VentasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DetalleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("ProductoID");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("VentaID");

                    b.HasKey("DetalleId")
                        .HasName("PK__VentasDe__6E19D6FA94348278");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("VentasDetalle", (string)null);
                });

            modelBuilder.Entity("GymApp.Models.Asistencia", b =>
                {
                    b.HasOne("GymApp.Models.Usuario", "User")
                        .WithMany("Asistencia")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Asistencias_Usuarios");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApp.Models.Congelamiento", b =>
                {
                    b.HasOne("GymApp.Models.Membresia", "Membresia")
                        .WithMany("Congelamientos")
                        .HasForeignKey("MembresiaId")
                        .IsRequired()
                        .HasConstraintName("FK_Congelamientos_Membresias");

                    b.HasOne("GymApp.Models.Usuario", "UsuarioEmpleado")
                        .WithMany("Congelamientos")
                        .HasForeignKey("UsuarioEmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK_Congelamientos_Empleado");

                    b.Navigation("Membresia");

                    b.Navigation("UsuarioEmpleado");
                });

            modelBuilder.Entity("GymApp.Models.Membresia", b =>
                {
                    b.HasOne("GymApp.Models.Plane", "Plan")
                        .WithMany("Membresia")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK_Membresias_Planes");

                    b.HasOne("GymApp.Models.Turno", "Turno")
                        .WithMany("Membresia")
                        .HasForeignKey("TurnoId")
                        .IsRequired()
                        .HasConstraintName("FK_Membresias_Turnos");

                    b.HasOne("GymApp.Models.Usuario", "User")
                        .WithMany("Membresia")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Membresias_Usuarios");

                    b.Navigation("Plan");

                    b.Navigation("Turno");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApp.Models.PagosMembresium", b =>
                {
                    b.HasOne("GymApp.Models.Membresia", "Membresia")
                        .WithMany("PagosMembresia")
                        .HasForeignKey("MembresiaId")
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_Membresias");

                    b.HasOne("GymApp.Models.Usuario", "UsuarioEmpleado")
                        .WithMany("PagosMembresia")
                        .HasForeignKey("UsuarioEmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_Empleado");

                    b.Navigation("Membresia");

                    b.Navigation("UsuarioEmpleado");
                });

            modelBuilder.Entity("GymApp.Models.Usuario", b =>
                {
                    b.HasOne("GymApp.Models.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GymApp.Models.VentasCabecera", b =>
                {
                    b.HasOne("GymApp.Models.Usuario", "User")
                        .WithMany("VentasCabeceraUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Ventas_Cliente");

                    b.HasOne("GymApp.Models.Usuario", "UsuarioEmpleado")
                        .WithMany("VentasCabeceraUsuarioEmpleados")
                        .HasForeignKey("UsuarioEmpleadoId")
                        .IsRequired()
                        .HasConstraintName("FK_Ventas_Empleado");

                    b.Navigation("User");

                    b.Navigation("UsuarioEmpleado");
                });

            modelBuilder.Entity("GymApp.Models.VentasDetalle", b =>
                {
                    b.HasOne("GymApp.Models.Producto", "Producto")
                        .WithMany("VentasDetalles")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_Detalle_Producto");

                    b.HasOne("GymApp.Models.VentasCabecera", "Venta")
                        .WithMany("VentasDetalles")
                        .HasForeignKey("VentaId")
                        .IsRequired()
                        .HasConstraintName("FK_Detalle_Venta");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("GymApp.Models.Membresia", b =>
                {
                    b.Navigation("Congelamientos");

                    b.Navigation("PagosMembresia");
                });

            modelBuilder.Entity("GymApp.Models.Plane", b =>
                {
                    b.Navigation("Membresia");
                });

            modelBuilder.Entity("GymApp.Models.Producto", b =>
                {
                    b.Navigation("VentasDetalles");
                });

            modelBuilder.Entity("GymApp.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GymApp.Models.Turno", b =>
                {
                    b.Navigation("Membresia");
                });

            modelBuilder.Entity("GymApp.Models.Usuario", b =>
                {
                    b.Navigation("Asistencia");

                    b.Navigation("Congelamientos");

                    b.Navigation("Membresia");

                    b.Navigation("PagosMembresia");

                    b.Navigation("VentasCabeceraUsers");

                    b.Navigation("VentasCabeceraUsuarioEmpleados");
                });

            modelBuilder.Entity("GymApp.Models.VentasCabecera", b =>
                {
                    b.Navigation("VentasDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
