services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gym_sql_server
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=PasswordSeguro123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  gymapp:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: gymapp_web
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sqldata,1433;Database=GymDB;User Id=sa;Password=PasswordSeguro123!;TrustServerCertificate=True;MultipleActiveResultSets=true
    ports:
      - "5000:8080"
    depends_on:
      - sqldata
    volumes:
      - ./gym_data/fotos_usuarios:/app/wwwroot/uploads/fotos

volumes:
  sql_data:
