version: '3.8'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gym_sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PasswordSeguro123! # Cambia esto por una contraseña fuerte
    ports:
      - "1433:1433" # Expone el puerto por defecto de SQL Server
    volumes:
      - sql_data:/var/opt/mssql # Esto asegura que no pierdas la BD si apagas el contenedor

  gymapp:
    build: .
    container_name: gymapp_web
    ports:
      - "5000:80"
    depends_on:
      - sqldata
    volumes:
      - ./fotos_usuarios:/app/wwwroot/uploads/fotos


volumes:
  sql_data: